IPNetwork: Allow partial addresses (again)
This introduces the new expand argument to IPNetwork class, so that
users can retain the previous behavior of netaddr < 1.0.0 optionally.

>>> import netaddr
>>> netaddr.IPNetwork('10/8')
Traceback (most recent call last):
  File "/home/tkajinam/git/python/netaddr/netaddr/strategy/ipv4.py", line 126, in str_to_int
    packed = _inet_pton(AF_INET, addr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: illegal IP address string passed to inet_pton

...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tkajinam/git/python/netaddr/netaddr/ip/__init__.py", line 1035, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % (addr,))
netaddr.core.AddrFormatError: invalid IPNetwork 10/8
>>> netaddr.IPNetwork('10/8', partial=True)
IPNetwork('10.0.0.0/8')